# Configuration du serveur
server:
  port: 8989
  shutdown: graceful

# Configuration de la gestion (Spring Boot Actuator)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
        application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0


# Configuration de l'application Spring
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalogue_service
              uri: ${CATALOGUE_SERVICE_URL:http://localhost:8081}
              predicates:
                  - Path=/catalogue/**
              filters:
                  - RewritePath=/catalogue/?(?<segment>.*), /${segment}
            - id: commande_service
              uri: ${COMMANDE_SERVICE_URL:http://localhost:8082}
              predicates:
                      - Path=/commandes/**
              filters:
                      - RewritePath=/commandes/?(?<segment>.*), /${segment}
            - id: openapi
              uri: http://localhost:${server.port}
              predicates:
                      - Path=/v3/api-docs/**
              filters:
                      - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN FIRST
# Configuration de Springdoc Swagger UI
  mvc:
    problemdetails:
      enabled: true
springdoc:
  swagger-ui:
    use-root-path: true
    urls:
#      - name: catalogue
#       url: /v3/api-docs/catalogue
#      - name: commande
#       url: /v3/api-docs/commande

# Configuration des logs pour déboguer
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}/%X{spanId}] %-5level %logger{36} - %msg%n"