# Configuration du serveur
server:
  port: 8989
  shutdown: graceful

# Configuration de la gestion (Spring Boot Actuator)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Configuration de l'application Spring
spring:
  application:
    name: api-gateway
  mvc:
    problemdetails:
      enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "GET,HEAD,POST,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        # Route pour catalogue_service
        - id: catalogue_service
          uri: ${CATALOGUE_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/catalogue/**
            - Method=GET,POST,OPTIONS
          filters:
            - RewritePath=/catalogue/?(?<segment>.*), /${segment}
        # Route pour commande_service
        - id: commande_service
          uri: ${COMMANDE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/commandes/**
            - Method=GET,POST,OPTIONS
          filters:
            - RewritePath=/commandes/?(?<segment>.*), /${segment}
            - AddResponseHeader=Access-Control-Allow-Origin, *
            - AddResponseHeader=Access-Control-Allow-Methods, GET,POST,OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, *
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN FIRST
# Configuration de Springdoc Swagger UI
springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: catalogue
        url: /v3/api-docs/catalogue
      - name: commande
        url: /v3/api-docs/commande

# Configuration des logs pour déboguer
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}/%X{spanId}] %-5level %logger{36} - %msg%n"