# Configuration du serveur
server:
  port: 8989
  shutdown: graceful

# Configuration de la gestion (Spring Boot Actuator)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Configuration de l'application Spring
spring:
  application:
    name: api-gateway
  mvc:
    problemdetails:
      enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false
      routes:
        # Route pour catalogue_service
        - id: catalogue_service
          uri: ${CATALOGUE_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/catalogue/**
          filters:
            - RewritePath=/catalogue/(?<segment>.*), /${segment}
        # Route pour commande_service
        - id: commande_service
          uri: ${COMMANDE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/commande/**
          filters:
            - RewritePath=/commande/(?<segment>.*), /${segment}
        # Route pour la documentation Swagger/OpenAPI de catalogue_service
        - id: openapi_catalogue
          uri: ${CATALOGUE_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/v3/api-docs/catalogue
          filters:
            - RewritePath=/v3/api-docs/catalogue, /v3/api-docs
        # Route pour la documentation Swagger/OpenAPI de commande_service
        - id: openapi_commande
          uri: ${COMMANDE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/v3/api-docs/commande
          filters:
            - RewritePath=/v3/api-docs/commande, /v3/api-docs

# Configuration de Springdoc Swagger UI
springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: catalogue
        url: /v3/api-docs/catalogue
      - name: commande
        url: /v3/api-docs/commande

# Configuration des logs
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}/%X{spanId}] %-5level %logger{36} - %msg%n"