name: 'KitabeShop'
services:
  catalogue_service:
    image: rayzobirame/kitabe-catalogue_service
    container_name: catalogue_service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://catalogue_db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
        catalogue_db:
          condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m

  commande_service:
    image: rayzobirame/kitabe-commande_service
    container_name: commande_service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - COMMANDE_CATALOGUE_SERVICE_URL=http://catalogue_service:8081
      - DB_URL=jdbc:postgresql://commande_db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - RABBITMQ_HOST=kitabe_rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      commande_db:
        condition: service_healthy
      kitabe_rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m