name: 'KitabeShop'

services:
  catalogue_db:
    image: postgres:16-alpine
    container_name: catalogue_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - kitabe_network

  commande_db:
    image: postgres:16-alpine
    container_name: commande_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "25432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - kitabe_network

  kitabe_rabbitmq:
    image: rabbitmq:3.12.11-management
    container_name: kitabe_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 30s
      retries: 10
    command: bash -c "chown -R rabbitmq:rabbitmq /var/lib/rabbitmq && rabbitmq-server"
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - kitabe_network

  notifications_db:
    image: postgres:16-alpine
    container_name: notifications_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "35432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - kitabe_network

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - kitabe_network

  keycloak_db:
    image: postgres:16-alpine
    container_name: keycloak_db
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    ports:
      - "45432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - kitabe_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    command: [ 'start-dev', '--http-port=9191', '--import-realm' ]
    container_name: keycloak
    hostname: keycloak
    volumes:
      - ./realm_config:/opt/keycloak/data/import
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin1234
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    ports:
      - "9191:9191"
    depends_on:
      keycloak_db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 2g
    networks:
      - kitabe_network

networks:
  kitabe_network:
    driver: bridge