name: Catalogue Service CI/CD

on:
  push:
    paths:
      - 'catalogue_Service/**'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalogue_Service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify
