name: Commande Service CI/CD

on:
  push:
    paths:
      - 'commande_service/**'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./commande_service
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/kitabe-commande_service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and publish docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          ./mvnw spring-boot:build-image -DskipTests
          echo "Entrain de pousser l'image docker $DOCKER_IMAGE_NAME dans le Docker hub.."
          docker push $DOCKER_IMAGE_NAME