name: Kitabe Web App

on:
  push:
    paths:
      - 'kitabe_web-app/**'
    branches:
      - '**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      working-directory: ./kitabe_web-app
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/kitabe_web-app
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and publish docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          ./mvnw spring-boot:build-image -DskipTests
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/kitabe_web-app